import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer, NavBar } from '@/components'
import { CartProvider } from '@/context/cart.provider'
import { NextUIProvider } from '@nextui-org/react'
import Page from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`block`}>
        <CartProvider>
          <NavBar/>
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  )
}
